apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-logs
  namespace: sakura-notes
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi