class NoteModel {
    constructor(id, email, content, tags) {
        this.id = id; // UUID generated by Laravel
        this.email = email; // email; (SELF IS QUERYABLE BY THIS!)
        this.content = content; // content of the note itself
        this.tags = tags; // tags (array) associated with that note; (SELF IS QUERYABLE BY THIS!)
    }
}

export default NoteModel;