services:
  redisdb:
    build:
      context: ../../services/db
    volumes:
      - database:/data/db
    env_file:
      - ./env/redisdb.env
    networks:
      - sakura-notes-internal-net
    ports:
      - '6379:6379'
  backend_1:
    build:
      context: ../../services/backend/sakura-notes-laravel-api
    volumes:
      - api-logs:/data/logs
    env_file:
      - ./env/api.env
    networks:
      - sakura-notes-net
      - sakura-notes-internal-net
    depends_on:
      - redisdb
  backend_2:
    build:
      context: ../../services/backend/sakura-notes-laravel-api
    volumes:
      - api-logs:/data/logs
    env_file:
      - ./env/api.env
    networks:
      - sakura-notes-net
      - sakura-notes-internal-net
    depends_on:
      - redisdb
  frontend:
    build:
      context: ../../services/frontend/sakura-notes-frontend
    env_file:
      - ./env/frontend.env
    networks:
      - sakura-notes-net
    depends_on:
      - backend_1
      - backend_2
  nginx:
    build:
      context: ../../services/nginx
    env_file:
      - ./env/nginx.env
    networks:
      - sakura-notes-net
    ports:
      - "8000:80"
      - "8001:443"
    depends_on:
      - backend_1
      - backend_2
      - frontend

volumes:
  database:
  api-logs:


networks:
  sakura-notes-net:
  sakura-notes-internal-net:
