apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: sakura-notes
spec:
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443