apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-db
  namespace: sakura-notes
spec:
  selector:
    matchLabels:
      app: redis-db
  serviceName: redis-db
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-db
    spec:
      containers:
        - name: redis-db
          image: sakura-notes-redis-db:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 6379
          env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: global-secrets
                key: REDIS_PASSWORD
          volumeMounts:
            - name: redis-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - "ReadWriteOnce"
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi