apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redisdb
  namespace: sakura-notes
spec:
  selector:
    matchLabels:
      app: redisdb
  serviceName: redisdb
  replicas: 1
  template:
    metadata:
      labels:
        app: redisdb
    spec:
      containers:
        - name: redisdb
          image: sakura-notes-redisdb:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 6379
          env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: global-secrets
                key: REDIS_PASSWORD
          volumeMounts:
            - name: redis-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - "ReadWriteOnce"
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi